<?php
$url_order = 'ASC';
if ($order_by == 'additional_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'document_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'document_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'additional_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'additional_comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'debit')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'credit')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'money')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>
<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>SỔ CÁI TÀI KHOẢN</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('detailaccount') ?>">Sổ cái</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">
    <div class="add-box">
        <a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Export Excel</a>
    </div>
    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
      <div class="add-box">
          <select id="sl_nv" name="sl_nv" style="width:80px">
           <option value="1">Quý I</option>
           <option value="2">Quý II</option>
           <option value="3">Quý III</option>
           <option value="4">Quý IV</option>
          </select>
          <select id="sl_tha" name="sl_tha" style="width:90px">
           <?php 
              for ($k=1; $k < 13; $k++) { 
                  echo '<option value="'.$k.'">Tháng '.$k.'</option>';
              }
           ?>
          </select>
          <select id="sl_na" name="sl_na" style="width:100px">
           <?php 
              $nam = date('Y');
              for ($k=($nam-5); $k < ($nam+5); $k++) { 
                  echo '<option value="'.$k.'">Năm '.$k.'</option>';
              }
           ?>
          </select>

          <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
          
      </div>
    </div>
    <div class="tablenav top">
      <div style="clear:both"></div>
      <div class="add-box">
                
          Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
          Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
           <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
          
      </div>

    </div>
    <div class="tablenav top">
        
        <div class="alignleft actions">
        <select name="m" id="chonloc">
          <option  value="18446744073709">Hiển thị tất cả</option>
          <option value="50">Hiển thị 50 giá trị</option>
                <option value="100">Hiển thị 100 giá trị</option>
                <option value="150">Hiển thị 150 giá trị</option>
                <option selected="selected" value="200">Hiển thị 200 giá trị</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
        </div>
        <div class="clearfix"></div>
        <div class="add-box">
            <select style="width: 150px;" name="sl_status" id="sl_status">
                <option value="">Tài khoản</option>
                <?php foreach ($account_parents as $account_parent) { ?>
                    <option value="<?php echo $account_parent->account_id ?>">
                        <?php
                         echo ($account_parent->account_parent > 0?'--':null) . " ".$account_parent->account_number.' - '.$account_parent->account_name 
                         ?>
                    </option>
                <?php } ?>
            </select>

            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');"> 
            
        </div>
      </div>

</div>

<table class="table_data" id="tblExport">
<thead>
    <tr>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_date','<?php echo $url_order ?>')">Ngày ghi sổ <?php if ($order_by == 'additional_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th colspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','document_number','<?php echo $url_order ?>')">Chứng từ <?php if ($order_by == 'document_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_comment','<?php echo $url_order ?>')">Diễn giải <?php if ($order_by == 'additional_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','debit','<?php echo $url_order ?>')">TK đối ứng <?php if ($order_by == 'debit'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th colspan="3" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money','<?php echo $url_order ?>')">Số tiền <?php if ($order_by == 'money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
    </tr>
    <tr>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','document_number','<?php echo $url_order ?>')">Số hiệu <?php if ($order_by == 'document_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','document_date','<?php echo $url_order ?>')">Ngày tháng <?php if ($order_by == 'document_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money','<?php echo $url_order ?>')">Nợ <?php if ($order_by == 'money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','money','<?php echo $url_order ?>')">Có <?php if ($order_by == 'money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
    </tr>
    
   </thead>
   <tbody>
    <?php 
    $tongno = 0; $tongco = 0;
    $nodauky[$trangthai]=isset($data_additional[$trangthai]['no']['dauky'])?$data_additional[$trangthai]['no']['dauky']:0;
    $codauky[$trangthai]=isset($data_additional[$trangthai]['co']['dauky'])?$data_additional[$trangthai]['co']['dauky']:0;
    
    ?>
    <tr style="font-weight:bold;" >
        <td class="fix text-center" colspan="5">Số dư đầu kỳ</td>
        <td class="fix text-right"><?php echo $lib->formatMoney($nodauky[$trangthai]) ?></td>
        <td class="fix text-right"><?php echo $lib->formatMoney($codauky[$trangthai]) ?></td>
        
    </tr>
    <?php
    foreach ($additionals as $additional) : 
        $no=0;$co=0;
        if ($additional->debit==$trangthai || in_array($additional->debit,$account_parent_data[$trangthai]) ) {
            $no = $additional->money;
            $tongno += $no;
            $tk = isset($account_data[$additional->credit])?$account_data[$additional->credit]:null;
        }
        else{
            $co = $additional->money;
            $tongco += $co;
            $tk = isset($account_data[$additional->debit])?$account_data[$additional->debit]:null;
        }
        
    ?>
    
        
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $additional->additional_id ?>" class="edit_tr">
            <td class="fix" id="additional_date_<?php echo $additional->additional_id; ?>"><?php echo $lib->hien_thi_ngay_thang($additional->additional_date); ?></td>
            <td class="fix" id="document_number_<?php echo $additional->additional_id; ?>"><?php echo $additional->document_number; ?></td>
            <td class="fix" id="document_date_<?php echo $additional->additional_id; ?>"><?php echo $lib->hien_thi_ngay_thang($additional->document_date); ?></td>
            
            <td class="fix" id="additional_comment_<?php echo $additional->additional_id; ?>"><?php echo $additional->additional_comment; ?></td>
            <td class="fix" data="<?php echo $additional->debit ?>" id="debit_<?php echo $additional->additional_id; ?>"><?php echo $tk; ?></td>
            <td class="fix text-right" id="money_<?php echo $additional->additional_id; ?>"><?php echo $lib->formatMoney($no); ?></td>
            <td class="fix text-right" id="money_<?php echo $additional->additional_id; ?>"><?php echo $lib->formatMoney($co); ?></td>
        </tr>


    <?php endforeach; ?>
        <tr style="font-weight:bold; color:red" >
            <td class="fix text-center" colspan="5">Tổng phát sinh</td>
            <td class="fix text-right"><?php echo $lib->formatMoney($tongno) ?></td>
            <td class="fix text-right"><?php echo $lib->formatMoney($tongco) ?></td>
            
        </tr>
        <tr style="font-weight:bold; color:red" >
            <td class="fix text-center" colspan="5">Số dư cuối kỳ</td>
            <td class="fix text-right"><?php echo $lib->formatMoney(max(0,$nodauky[$trangthai]+$tongno-$tongco-$codauky[$trangthai])) ?></td>
            <td class="fix text-right"><?php echo $lib->formatMoney(max(0,$codauky[$trangthai]+$tongco-$tongno-$nodauky[$trangthai])) ?></td>
        </tr>
     
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<script type="text/javascript">

var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');
var s = "<?php echo $trangthai ?>";
$('#sl_status option[value='+s+']').attr('selected','selected');


</script>

<script type="text/javascript">


$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Phát sinh",
    hide: 'fold',
    show: 'blind'
});



$(".show").click(function(){
    $("#winpopup").dialog({
        draggable:true,
        modal: true,
        autoOpen: false,
        width: "90%",
        resizable: false,
        position: "top",
        title:'Chi tiết',
        buttons: {
            OK: function() {
                $( this ).dialog( "close" );
            },
            Cancel: function() {
                $( this ).dialog( "close" );
            }
        }
    });
    $("#winpopup").load($(this).attr('href'));
    $("#winpopup").dialog("open");
    return false;
});

var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".ngay").datepicker(pickerOpay2);


var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');
var nv = "<?php echo $nv ?>";
$('#sl_nv option[value='+nv+']').attr('selected','selected');
var tha = "<?php echo $tha ?>";
$('#sl_tha option[value='+tha+']').attr('selected','selected');
var na = "<?php echo $na ?>";
$('#sl_na option[value='+na+']').attr('selected','selected');


var pickerOpts3 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts3);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);

$('#sl_nv').change(function(){
      var q = $(this).val();
      var y = $('#sl_na').val();
      var m,n;
      
      switch(q) {
        case "1":
            m=1;
            n=3;
            break;
        case "2":
            m=4;
            n=6;
            break;
        case "3":
            m=7;
            n=9;
            break;
        case "4":
            m=10;
            n=12;
            break;
      }

      var firstDay = new Date(y, m-1, 1);
      var lastDay = new Date(y, n, 0);

      $('#batdau').datepicker("setDate", firstDay );
      $('#ketthuc').datepicker("setDate", lastDay );

  });

$('#sl_tha').change(function(){
      var m = $(this).val();
      var y = $('#sl_na').val();
      var firstDay = new Date(y, m-1, 1);
      var lastDay = new Date(y, m, 0);

      $('#batdau').datepicker("setDate", firstDay );
      $('#ketthuc').datepicker("setDate", lastDay );

  });

  $('#sl_na').change(function(){
      var y = $(this).val();
      var m = $('#sl_tha').val();
      var firstDay = new Date(y, m-1, 1);
      var lastDay = new Date(y, m, 0);

      $('#batdau').datepicker("setDate", firstDay );
      $('#ketthuc').datepicker("setDate", lastDay );

  });

</script>

