<?php
$url_order = 'ASC';
if ($order_by == 'customer_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_code')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'customer_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>
<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>BẢNG TỔNG HỢP CÔNG NỢ PHẢI THU</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('customer') ?>">Tổng hợp công nợ phải thu</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <?php if(!isset($disable_control)){ ?>
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <?php } ?>
    </div>
    <div class="tablenav top">
      <div class="add-box">
          <select id="sl_nv" name="sl_nv" style="width:80px">
           <option value="1">Quý I</option>
           <option value="2">Quý II</option>
           <option value="3">Quý III</option>
           <option value="4">Quý IV</option>
          </select>
          <select id="sl_tha" name="sl_tha" style="width:90px">
           <?php 
              for ($k=1; $k < 13; $k++) { 
                  echo '<option value="'.$k.'">Tháng '.$k.'</option>';
              }
           ?>
          </select>
          <select id="sl_na" name="sl_na" style="width:100px">
           <?php 
              $nam = date('Y');
              for ($k=($nam-5); $k < ($nam+5); $k++) { 
                  echo '<option value="'.$k.'">Năm '.$k.'</option>';
              }
           ?>
          </select>

          <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
          
      </div>
    </div>
    <div class="tablenav top">
      <div style="clear:both"></div>
      <div class="add-box">
                
          Từ  <input style="width:80px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
          Đến  <input style="width:80px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
           <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
          
      </div>

    </div>
    <div class="tablenav top">
        
        <div class="alignleft actions">
        <select name="m" id="chonloc">
          <option  value="18446744073709">Hiển thị tất cả</option>
          <option value="50">Hiển thị 50 giá trị</option>
                <option value="100">Hiển thị 100 giá trị</option>
                <option value="150">Hiển thị 150 giá trị</option>
                <option selected="selected" value="200">Hiển thị 200 giá trị</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
        </div>
        <div style="clear:both"></div>
        <div class="add-box">
            <select style="width: 150px;" name="sl_status" id="sl_status">
                <option value="">Khách hàng</option>
                <?php foreach ($customer_lists as $customer) { ?>
                    <option value="<?php echo $customer->customer_id ?>"><?php echo $customer->customer_name ?></option>
                <?php } ?>
            </select>

            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');"> 
            
        </div>
        

      </div>

</div>

<table class="table_data" id="tblExport">
<thead>
    <tr>
        <th  rowspan="2" class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'customer_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_code','<?php echo $url_order ?>')">Mã khách hàng <?php if ($order_by == 'customer_code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_company','<?php echo $url_order ?>')">Tên khách hàng <?php if ($order_by == 'customer_company'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th rowspan="2" class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','customer_mst','<?php echo $url_order ?>')">MST <?php if ($order_by == 'customer_mst'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th colspan="2" class="fix">
            <a class="sort">Đầu kỳ</a>
        </th>
        <th colspan="2" class="fix">
            <a class="sort">Phát sinh</a>
        </th>
        <th colspan="2" class="fix">
            <a class="sort">Cuối kỳ</a>
        </th>
    </tr>
    <tr>
        <th class="fix">
            <a class="sort">Nợ</a>
        </th>
        <th class="fix">
            <a class="sort">Có</a>
        </th>
        <th class="fix">
            <a class="sort">Nợ</a>
        </th>
        <th class="fix">
            <a class="sort">Có</a>
        </th>
        <th class="fix">
            <a class="sort">Nợ</a>
        </th>
        <th class="fix">
            <a class="sort">Có</a>
        </th>
    </tr>
    
   </thead>
   <tbody>
    <?php 
    $tongno_dauky=0;$tongco_dauky=0;$tongno_ps=0;$tongco_ps=0;$tongno_cuoiky=0;$tongco_cuoiky=0;
    foreach ($customers as $customer) : 
    $no_dauky = isset($data_debit[$customer->customer_id]['dauky_no'])?$data_debit[$customer->customer_id]['dauky_no']:"";
    $co_dauky = isset($data_debit[$customer->customer_id]['dauky_co'])?$data_debit[$customer->customer_id]['dauky_co']:"";
    $no_phatsinh = isset($data_debit[$customer->customer_id]['no'])?$data_debit[$customer->customer_id]['no']:"";
    $co_phatsinh = isset($data_debit[$customer->customer_id]['co'])?$data_debit[$customer->customer_id]['co']:"";
    
    if ($no_dauky>=$co_dauky) {
        $no_dauky = $no_dauky-$co_dauky;
        $co_dauky = "";
    }
    else{
        $co_dauky = $co_dauky-$no_dauky;
        $no_dauky = "";
    }

    $no_cuoiky = $no_dauky+$no_phatsinh;
    $co_cuoiky = $co_dauky+$co_phatsinh;

    if ($no_cuoiky>=$co_cuoiky) {
        $no_cuoiky = $no_cuoiky-$co_cuoiky;
        $co_cuoiky = "";
    }
    else{
        $co_cuoiky = $co_cuoiky-$no_cuoiky;
        $no_cuoiky = "";
    }
    
    $tongno_dauky+=$no_dauky;
    $tongco_dauky+=$co_dauky;
    $tongno_ps+=$no_phatsinh;
    $tongco_ps+=$co_phatsinh;
    $tongno_cuoiky+=$no_cuoiky;
    $tongco_cuoiky+=$co_cuoiky;

    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $customer->customer_id ?>" class="edit_tr">
            <td  class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="customer_code_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_code; ?></td>
            <td class="fix" id="customer_company_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_company; ?></td>
            <td class="fix" id="customer_mst_<?php echo $customer->customer_id; ?>"><?php echo $customer->customer_mst; ?></td>
            <td class="fix text-right"><?php echo $lib->formatMoney($no_dauky); ?></td>
            <td class="fix text-right"><?php echo $lib->formatMoney($co_dauky); ?></td>
            <td class="fix text-right"><?php echo $lib->formatMoney($no_phatsinh); ?></td>
            <td class="fix text-right"><?php echo $lib->formatMoney($co_phatsinh); ?></td>
            <td class="fix text-right"><?php echo $lib->formatMoney($no_cuoiky); ?></td>
            <td class="fix text-right"><?php echo $lib->formatMoney($co_cuoiky); ?></td>
        </tr>


    <?php endforeach; ?>
        <tr style="font-weight:bold; color:red" >
                <td class="fix" colspan="4">Tổng cộng</td>
                <td class="fix text-right"><?php echo $lib->formatMoney($tongno_dauky); ?></td>
                <td class="fix text-right"><?php echo $lib->formatMoney($tongco_dauky); ?></td>
                <td class="fix text-right"><?php echo $lib->formatMoney($tongno_ps); ?></td>
                <td class="fix text-right"><?php echo $lib->formatMoney($tongco_ps); ?></td>
                <td class="fix text-right"><?php echo $lib->formatMoney($tongno_cuoiky); ?></td>
                <td class="fix text-right"><?php echo $lib->formatMoney($tongco_cuoiky); ?></td>
            </tr>
     
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<script type="text/javascript">

var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');
var s = "<?php echo $trangthai ?>";
$('#sl_status option[value='+s+']').attr('selected','selected');


</script>


<script type="text/javascript">

var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".ngay").datepicker(pickerOpay2);


var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');
var nv = "<?php echo $nv ?>";
$('#sl_nv option[value='+nv+']').attr('selected','selected');
var tha = "<?php echo $tha ?>";
$('#sl_tha option[value='+tha+']').attr('selected','selected');
var na = "<?php echo $na ?>";
$('#sl_na option[value='+na+']').attr('selected','selected');


var pickerOpts3 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts3);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);

$('#sl_nv').change(function(){
      var q = $(this).val();
      var y = $('#sl_na').val();
      var m,n;
      
      switch(q) {
        case "1":
            m=1;
            n=3;
            break;
        case "2":
            m=4;
            n=6;
            break;
        case "3":
            m=7;
            n=9;
            break;
        case "4":
            m=10;
            n=12;
            break;
      }

      var firstDay = new Date(y, m-1, 1);
      var lastDay = new Date(y, n, 0);

      $('#batdau').datepicker("setDate", firstDay );
      $('#ketthuc').datepicker("setDate", lastDay );

  });

$('#sl_tha').change(function(){
      var m = $(this).val();
      var y = $('#sl_na').val();
      var firstDay = new Date(y, m-1, 1);
      var lastDay = new Date(y, m, 0);

      $('#batdau').datepicker("setDate", firstDay );
      $('#ketthuc').datepicker("setDate", lastDay );

  });

  $('#sl_na').change(function(){
      var y = $(this).val();
      var m = $('#sl_tha').val();
      var firstDay = new Date(y, m-1, 1);
      var lastDay = new Date(y, m, 0);

      $('#batdau').datepicker("setDate", firstDay );
      $('#ketthuc').datepicker("setDate", lastDay );

  });



    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        changeMonth: true,
        changeYear: true,
        dateFormat: 'mm/yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function() {
            var month = parseInt($("#ui-datepicker-div .ui-datepicker-month :selected").val());
            var year = parseInt($("#ui-datepicker-div .ui-datepicker-year :selected").val());
            $(this).datepicker('setDate', new Date(year, month, 1));
         },
         
    };  
    $("#ngaycapnhat").datepicker(pickerOpts4);


    $(".monthPicker").focus(function () {
        $(".ui-datepicker-calendar").hide();
        $("#ui-datepicker-div").position({
            my: "center top",
            at: "center bottom",
            of: $(this)
        });    
    });

$('#update_price').click(function(){
    var val = $('#ngaycapnhat').val();

    $.ajax({
        url: '<?php echo BASE_URL ?>/debit/updateprice',
        type: 'POST',
        data: {val:val},
        success:function(data){
            alert(data);
        }
    });
});
</script>

