<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

  <title><?php echo isset($title) ? $title : null ?></title>

  <meta name="keywords" content="Kế toán, tài chính, thu chi, ngân hàng, kho, nhập xuất tồn, tài sản, lương, báo cáo thuế">

  <meta name="description" content="<?php echo isset($title) ? $title.' - ' : null ?>Logistics - Vận chuyển - Thủ tục hải quan - Manifest - Container">

  <meta name="generator" content="Viet Trade">

  <link href="<?php BASE_URL ?>/public/img/logo.png" rel="shortcut icon" type="image/vnd.microsoft.icon">

  <!-- Tell the browser to be responsive to screen width -->

  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <!-- Bootstrap 3.3.6 -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/bootstrap/css/bootstrap.min.css">

  <!-- Font Awesome -->

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Ionicons -->

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

  <!-- Morris chart -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/plugins/morris/morris.css">

  <!-- Theme style -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/dist/css/AdminLTE.min.css">

  <!-- AdminLTE Skins. Choose a skin from the css/skins

       folder instead of downloading all of them to reduce the load. -->

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/adminbar/dist/css/skins/_all-skins.min.css">



  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->

  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

  <!--[if lt IE 9]>

  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>

  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

  <![endif]-->

  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/css/style.css">

  <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/public/js/ui/jquery-ui.css">

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery-1.7.2.min.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/ui/jquery-ui.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/html5.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.form.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.validate.min.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/custom.js"></script>

  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/localization/messages_vi.js"></script>

  <script type="text/javascript" src="<?php echo BASE_URL ?>/public/js/jquery.battatech.excelexport.js"></script>

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/js/chosen/chosen.css">
  <script src="<?php echo BASE_URL ?>/public/js/chosen/chosen.jquery.js" type="text/javascript"></script>

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/css/component.css">
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.stickyheader.js"></script>
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/jquery.ba-throttle-debounce.min.js"></script>

  <!-- InputMask -->
<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/input-mask/jquery.inputmask.js"></script>
<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/input-mask/jquery.inputmask.extensions.js"></script>

  <link rel="stylesheet" href="<?php BASE_URL ?>/public/css/head.css">
  <script type="text/javascript" src="<?php BASE_URL ?>/public/js/head.js"></script>
  <script type="text/javascript">
  var check_lock_user = 0;

    $.ajax({

      type: "POST",

      url: "<?php echo BASE_URL ?>/admin/checklockuser",

      data: "data=<?php echo isset($_SESSION['userid_logined'])?$_SESSION['userid_logined']:0 ?>", // or any data you want to send

      cache: false,

      success: function(html){

        check_lock_user = html;

        if (check_lock_user==1) {

          $.ajax({

            type: "GET",

            url: "<?php echo BASE_URL ?>/user/logout",

            data: "data=1", // or any data you want to send

            cache: false,

            success: function(html){

              window.location.href = "<?php echo BASE_URL ?>";

            }

          });

        };

      }

    });
    
  <?php if (isset($_SESSION['userid_logined']) && ($_SESSION['role_logined'] != 1 && $_SESSION['role_logined'] != 2) ) { ?>

      $(document).ready(function(){
          $('#doaction').attr('disabled',true);
          $('#action').attr('disabled',true);
          $('.btn-danger').each(function(){
            if ($(this).attr("onclick")) {
              $(this).hide();
            }
          });

      });
    <?php } ?>
  </script>
</head>

<body class="hold-transition skin-blue sidebar-mini">

<div class="wrapper">

  <div id="ajax_loader" style="position: fixed; left: 50%; top: 50%; margin-left : -16px; margin-top : -16px; z-index:999999;">

      <img src="<?php echo BASE_URL ?>/public/img/loader-gears.gif">

  </div>

  <header class="main-header">

    <!-- Logo -->

    <a href="<?php echo BASE_URL ?>" class="logo">

      <!-- mini logo for sidebar mini 50x50 pixels -->

      <span class="logo-mini"><b>AMS</b></span>

      <!-- logo for regular state and mobile devices -->

      <span class="logo-lg"><b>AMS</b></span>

    </a>

    <!-- Header Navbar: style can be found in header.less -->

    <nav class="navbar navbar-static-top">

      <!-- Sidebar toggle button-->

      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">

        <span class="sr-only">Toggle navigation</span>

      </a>
      <div style="color:white;float: left;margin-top: 15px;">

        <i class="fa fa-user-circle-o"></i>  <?php echo isset($_SESSION['company'])?$_SESSION['company']:null ?>

      </div>


      <div class="navbar-custom-menu">

        

          <!-- Messages: style can be found in dropdown.less-->

          

          <!-- Notifications: style can be found in dropdown.less -->

          

          <!-- Tasks: style can be found in dropdown.less -->

          

          <!-- User Account: style can be found in dropdown.less -->

          <ul class="nav navbar-nav">

          <!-- Messages: style can be found in dropdown.less-->

          <li class="dropdown messages-menu">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

              <i class="fa fa-envelope-o"></i>

              <span class="label label-success">4</span>

            </a>

          </li>

          <!-- Notifications: style can be found in dropdown.less -->

          <li class="dropdown notifications-menu">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

              <i class="fa fa-bell-o"></i>

              <span class="label label-warning">10</span>

            </a>

          </li>

          <!-- Tasks: style can be found in dropdown.less -->

          <li class="dropdown tasks-menu">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

              <i class="fa fa-flag-o"></i>

              <span class="label label-danger">9</span>

            </a>

          </li>

          <!-- User Account: style can be found in dropdown.less -->

          <li class="dropdown user user-menu">

            <!-- Kiem tra dang nhap -->

            <?php 

            if (isset($_SESSION['user_logined'])) {

              ?>

              <a class="logined" href="<?php echo $this->url('user/logout') ?>">&nbsp; | Logout</a><a class="logined" href="<?php echo BASE_URL.'/user/info/'.$_SESSION['userid_logined'] ?>"><b><i><?php echo $_SESSION['user_logined']; ?> </i></b></a>

              <?php

            }

            else{

              ?>

              <a class="logined" href="<?php echo $this->url('user/login') ?>">Login</a>

              <?php

            }

            ?>

            <!-- end -->

          </li>

          <!-- Control Sidebar Toggle Button -->

        </ul>

          

          <!-- Control Sidebar Toggle Button -->

          

      </div>

    </nav>

  </header>

  <!-- Left side column. contains the logo and sidebar -->

  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->

    <section class="sidebar">

      

      <!-- sidebar menu: : style can be found in sidebar.less -->

      <ul class="sidebar-menu">

        <?php if ($_SESSION) { ?>

        <li class="header">QUẢN TRỊ</li>

        <li class="treeview">

          <a data="admin" data-role="admin" href="<?php echo $this->url('admin') ?>">

            <i class="fa fa-home"></i> <span>Trang chủ</span>

          </a>

        </li>

        

        <li class="treeview">

          <a  data="#" href="#">

            <i class="fa fa-dollar"></i>

            <span>Kế toán</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">
            <li class="treeview">
              <a  data="#" href="#">
                <i class="fa fa-money"></i>
                <span>Quỹ</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="receiptcash" data-role="receiptcash" href="<?php echo $this->url('receiptcash') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phiếu thu</a></li>
                <li><a data="paycash" data-role="paycash" href="<?php echo $this->url('paycash') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phiếu chi</a></li>
                <li><a data="internaltransfer" data-role="internaltransfer" href="<?php echo $this->url('internaltransfer') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chuyển tiền nội bộ</a></li>
                <li><a data="detailcash" data-role="detailcash" href="<?php echo $this->url('detailcash') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Sổ quỹ</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a  data="#" href="#">
                <i class="fa fa-bank"></i>
                <span>Tiền gửi</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="bank" data-role="bank" href="<?php echo $this->url('bank') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Danh mục ngân hàng</a></li>
                <li><a data="receiptbank" data-role="receiptbank" href="<?php echo $this->url('receiptbank') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Thu tiền</a></li>
                <li><a data="paybank" data-role="paybank" href="<?php echo $this->url('paybank') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Thanh toán trong nước</a></li>
                <li><a data="payexbank" data-role="payexbank" href="<?php echo $this->url('payexbank') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Thanh toán nước ngoài</a></li>
                <li><a data="paytaxbank" data-role="paytaxbank" href="<?php echo $this->url('paytaxbank') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Nộp thuế</a></li>
                <li><a data="detailbank" data-role="detailbank" href="<?php echo $this->url('detailbank') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Sổ tiền gửi NH</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a  data="#" href="#">
                <i class="fa fa-shopping-cart"></i>
                <span>Mua hàng</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="supplier" data-role="supplier" href="<?php echo $this->url('supplier') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Danh mục nhà cung cấp</a></li>
                <li><a data="invoicebuy" data-role="invoicebuy" href="<?php echo $this->url('invoicebuy') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Mua hàng nhập khẩu</a></li>
                <li><a data="invoicepurchase" data-role="invoicepurchase" href="<?php echo $this->url('invoicepurchase') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Mua hàng trong nước</a></li>
                <li><a data="servicebuy" data-role="servicebuy" href="<?php echo $this->url('servicebuy') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Mua hàng dịch vụ</a></li>
                <li><a data="debitpay" data-role="debitpay" href="<?php echo $this->url('debitpay') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Tổng hợp công nợ phải trả</a></li>
                <li><a data="debitpaydetail" data-role="debitpaydetail" href="<?php echo $this->url('debitpaydetail') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi tiết công nợ phải trả</a></li>
                <li><a data="detailbuy" data-role="detailbuy" href="<?php echo $this->url('detailbuy') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Nhật ký mua hàng</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a  data="#" href="#">
                <i class="fa fa-wpforms"></i>
                <span>Bán hàng</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="customer" data-role="customer" href="<?php echo $this->url('customer') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Danh mục khách hàng</a></li>
                <li><a data="invoicesell" data-role="invoicebuy" href="<?php echo $this->url('invoicesell') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Hóa đơn bán hàng</a></li>
                <li><a data="debitreceive" data-role="debitreceive" href="<?php echo $this->url('debitreceive') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Tổng hợp công nợ phải thu</a></li>
                <li><a data="debitreceivedetail" data-role="debitreceivedetail" href="<?php echo $this->url('debitreceivedetail') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi tiết công nợ phải thu</a></li>
                <li><a data="detailsell" data-role="detailsell" href="<?php echo $this->url('detailsell') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Nhật ký bán hàng</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a  data="#" href="#">
                <i class="fa fa-home"></i>
                <span>Kho</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="items" data-role="items" href="<?php echo $this->url('items') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Danh mục Hàng hóa, dịch vụ</a></li>
                <li><a data="house" data-role="house" href="<?php echo $this->url('house') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Danh mục kho</a></li>
                <li><a data="stockdetail" data-role="stockdetail" href="<?php echo $this->url('stockdetail') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Chi tiết hàng hóa</a></li>
                <li><a data="stock" data-role="stock" href="<?php echo $this->url('stock') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Tổng hợp tồn kho</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a  data="#" href="#">
                <i class="fa fa-users"></i>
                <span>Lương</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="department" data-role="department" href="<?php echo $this->url('department') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Danh sách phòng ban</a></li>
                <li><a data="staff" data-role="staff" href="<?php echo $this->url('staff') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Danh sách nhân viên</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a  data="#" href="#">
                <i class="fa fa-archive"></i>
                <span>Tài sản</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="asset" data-role="asset" href="<?php echo $this->url('asset') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Khai báo TSCĐ</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a  data="#" href="#">
                <i class="fa fa-wrench"></i>
                <span>CCDC</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="asset" data-role="asset" href="<?php echo $this->url('asset') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Khai báo CCDC</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a  data="#" href="#">
                <i class="fa fa-file-text-o"></i>
                <span>Tổng hợp</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="account" data-role="account" href="<?php echo $this->url('account') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Danh mục tài khoản</a></li>
                <li><a data="additionalother" data-role="additionalother" href="<?php echo $this->url('additionalother') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Phiếu kế toán</a></li>
                <li><a data="additional" data-role="additional" href="<?php echo $this->url('additional') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Nhật ký chung</a></li>
                <li><a data="detailaccount" data-role="detailaccount" href="<?php echo $this->url('detailaccount') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Sổ chi tiết</a></li>
                <li><a data="forward" data-role="forward" href="<?php echo $this->url('forward') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Kết chuyển lãi lỗ</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a  data="#" href="#">
                <i class="fa fa-calculator"></i>
                <span>Báo cáo thuế</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="invoicein" data-role="invoicein" href="<?php echo $this->url('invoicein') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bảng kê hóa đơn mua vào</a></li>
                <li><a data="invoiceout" data-role="invoiceout" href="<?php echo $this->url('invoiceout') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bảng kê hóa đơn bán ra</a></li>
                <li><a data="invoicetax" data-role="invoicetax" href="<?php echo $this->url('invoicetax') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Tờ khai thuế GTGT</a></li>
              </ul>
            </li>
            
            <li class="treeview">
              <a  data="#" href="#">
                <i class="fa fa-line-chart"></i>
                <span>Báo cáo tài chính</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-right pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a data="balanceadditional" data-role="balanceadditional" href="<?php echo $this->url('balanceadditional') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bảng cân đối phát sinh</a></li>
                <li><a data="balanceaccounting" data-role="balanceaccounting" href="<?php echo $this->url('balanceaccounting') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Bảng cân đối kế toán</a></li>
                <li><a data="balanceresult" data-role="balanceresult" href="<?php echo $this->url('balanceresult') ?>"><i class="fa fa-fw fa-caret-right text-aqua"></i>Báo cáo KQHĐKD</a></li>
              </ul>
            </li>

            
            
          </ul>

        </li>

        
        <li class="treeview">

          <a  data="#" href="#">

            <i class="fa fa-cogs"></i>

            <span>Hệ thống</span>

            <span class="pull-right-container">

              <i class="fa fa-angle-right pull-right"></i>

            </span>

          </a>

          <ul class="treeview-menu">

            <li><a data="info" data-role="info" href="<?php echo $this->url('info') ?>"><i class="fa fa-fw fa-info-circle text-aqua"></i>Thông tin doanh nghiệp</a></li>

            <li><a data="user" data-role="user" href="<?php echo $this->url('user') ?>"><i class="fa fa-fw fa-user text-aqua"></i>Tài khoản</a></li>

            <li><a data="permission" data-role="permission" href="<?php echo $this->url('permission') ?>"><i class="fa fa-fw fa-lock text-aqua"></i>Phân quyền</a></li>

            <li><a data="backup" data-role="backup" href="<?php echo $this->url('backup') ?>"><i class="fa fa-fw fa-refresh text-aqua"></i>Sao lưu & Phục hồi</a></li>

            <li><a data="update" data-role="update" href="<?php echo $this->url('update') ?>"><i class="fa fa-fw fa-hdd-o text-aqua"></i>Cập nhật phần mềm</a></li>

          </ul>

        </li>

        

        

        <?php } ?>


      </ul>

    </section>

    <!-- /.sidebar -->

  </aside>



  <!-- Content Wrapper. Contains page content -->

  <div class="content-wrapper">

    <!-- Content Header (Page header) -->

    



    <!-- Main content -->

    <section class="content">

      <!-- Small boxes (Stat box) -->

      <div class="row">

        <div class="col-md-12 fixed-scrollbar">

          <?php echo $content; ?>

        </div>

        <!-- ./col --> 

      </div>

      <!-- /.row -->



    </section>

    <!-- /.content -->

    

  </div>

  <!-- /.content-wrapper -->

  <footer class="main-footer">

    <div class="pull-right hidden-xs">

      <b>Version</b> 3.0

    </div>

    <span style="font-size:5px">Powered by <a target="_blank" style="color:#fff" href="http://www.tinhoctainha.com">Dịch vụ Tin Học Tại Nhà</a></span>

  </footer>



  <!-- Control Sidebar -->

  

  <!-- /.control-sidebar -->

  <!-- Add the sidebar's background. This div must be placed

       immediately after the control sidebar -->

  <div class="control-sidebar-bg"></div>

</div>

<!-- ./wrapper -->





<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

<script>

  $.widget.bridge('uibutton', $.ui.button);

</script>

<!-- Bootstrap 3.3.6 -->

<script src="<?php BASE_URL ?>/public/js/adminbar/bootstrap/js/bootstrap.min.js"></script>

<!-- Morris.js charts -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/morris/morris.min.js"></script>

<!-- jQuery Knob Chart -->

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/knob/jquery.knob.js"></script>

<!-- daterangepicker -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/daterangepicker/daterangepicker.js"></script>


<!-- Bootstrap WYSIHTML5 -->

<script src="<?php BASE_URL ?>/public/js/adminbar/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

<!-- AdminLTE App -->

<script src="<?php BASE_URL ?>/public/js/adminbar/dist/js/app.min.js"></script>

<!-- AdminLTE dashboard demo (This is only for demo purposes) -->

<!-- AdminLTE for demo purposes -->

<script src="<?php BASE_URL ?>/public/js/adminbar/dist/js/demo.js"></script>

<script type="text/javascript">

$( document ).ajaxStart(function() {

  $("#ajax_loader").fadeIn(200);

  $('input[type="submit"]').attr('disabled',true);
  $('button[type="submit"]').attr('disabled',true);

});

$( document ).ajaxComplete(function() {

  $("#ajax_loader").fadeOut(200);

  $('input[type="submit"]').attr('disabled',false);
  $('button[type="submit"]').attr('disabled',false);

});

$(window).load(function() { 

  $("#ajax_loader").fadeOut(200);

  var data_permission = jQuery.parseJSON('<?php echo isset($_SESSION["user_permission"])?$_SESSION["user_permission"]:"" ?>');

  $('.sidebar-menu a:not([data="#"])').hide();
  $.each(data_permission, function(i, item) {
      $('.sidebar-menu a[data-role="'+data_permission[i]+'"]').show();
  });
  $('.sidebar-menu a[data-role="admin"]').show();
  $('.sidebar-menu a[data-role="support"]').show();

});


$('.add_button').click(function(){
  $('.date_mask').val("<?php echo date('d/m/Y') ?>");

  $('.date_mask:first').keyup(function(){
    $('.date_mask:not(:first)').val($(this).val());
  });
});
</script>

</body>

</html>