<?php
$url_order = 'ASC';
if ($order_by == 'additional_other_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'additional_other_document_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'additional_other_document_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'additional_other_additional_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'additional_other_comment')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'additional_other_debit')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'additional_other_credit')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'additional_other_money')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

    $i = $sonews*$page-($sonews-1);

?>
<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>PHIẾU KẾ TOÁN</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('additional') ?>">Phiếu kế toán</a></li>
  </ol>
</section>
<div id="content" style="padding:5px;">

    <div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
        <?php if(!isset($disable_control)){ ?>
        <div class="add-box"><a class="add_button" id="btnExport" ><i class="fa fa-download"></i> Xuất</a></div>
        <div class="add-box"><a class="add_button" id="import_excel" href="<?= $this->url('additional/import')?>"><i class="fa fa-upload"></i> Nhập</a></div>
        <div class="add-box"><a class="add_button" onClick="add_click();"><i class="fa fa-plus"></i> Thêm mới</a></div>
        <?php } ?>
    </div>
    <div class="tablenav top">
        <div class="add-box">
                  
            Từ  <input style="width:100px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:100px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>
        <div class="add-box">
            Từ tháng <input class="monthPicker" style="width:90px" type="search" name="chonngaytao" id="chonngaytao" placeholder="Chọn tháng" <?php if(isset($ngaytao)) echo "value='$ngaytao'"; ?> >    
            Đến tháng <input class="monthPicker" style="width:90px" type="search" name="chonngaytaobatdau" id="chonngaytaobatdau" placeholder="Chọn tháng" <?php if(isset($ngaytaobatdau)) echo "value='$ngaytaobatdau'"; ?> >  

            <input type="button" name="chon" id="chon" class="button" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">        
                                        
        </div>
        
        <?php if(!isset($disable_control)){ ?>
        <div class="alignleft actions">
            <select name="action" id="action">
                <option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
        </div>
        <?php } ?>
        <div class="alignleft actions">
        <select name="m" id="chonloc">
          <option  value="18446744073709">Hiển thị tất cả</option>
          <option value="50">Hiển thị 50 giá trị</option>
                <option value="100">Hiển thị 100 giá trị</option>
                <option value="150">Hiển thị 150 giá trị</option>
                <option selected="selected" value="200">Hiển thị 200 giá trị</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
        </div>
        <div class="add-box">
            <select style="width: 150px;" name="sl_status" id="sl_status">
                <option value="">Tài khoản</option>
                <?php foreach ($account_parents as $account_parent) { ?>
                    <option value="<?php echo $account_parent->account_id ?>">
                        <?php
                         echo ($account_parent->account_parent > 0?'--':null) . " ".$account_parent->account_number.' - '.$account_parent->account_name 
                         ?>
                    </option>
                <?php } ?>
            </select>

            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');"> 
            
        </div>

      </div>

</div>

<table class="table_data" id="tblExport">
<thead>
    <tr>
        <th class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix" >
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_other_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'additional_other_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_other_document_number','<?php echo $url_order ?>')">Số chứng từ <?php if ($order_by == 'additional_other_document_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_other_document_date','<?php echo $url_order ?>')">Ngày chứng từ <?php if ($order_by == 'additional_other_document_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_other_additional_date','<?php echo $url_order ?>')">Ngày phát sinh <?php if ($order_by == 'additional_other_additional_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_other_comment','<?php echo $url_order ?>')">Nội dung <?php if ($order_by == 'additional_other_comment'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_other_debit','<?php echo $url_order ?>')">Nợ <?php if ($order_by == 'additional_other_debit'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_other_credit','<?php echo $url_order ?>')">Có <?php if ($order_by == 'additional_other_credit'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_other_money','<?php echo $url_order ?>')">Số tiền <?php if ($order_by == 'additional_other_money'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_other_tax_percent','<?php echo $url_order ?>')">Thuế GTGT <?php if ($order_by == 'additional_other_tax_percent'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','additional_other_tax','<?php echo $url_order ?>')">Tiền thuế GTGT <?php if ($order_by == 'additional_other_tax'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <?php if(!isset($disable_control)){ ?>
        <th class="fix"></th>
        <?php } ?>
    </tr>
    
   </thead>
   <tbody>
    <?php 
    $tong = 0; $tongvat=0;
    foreach ($additionals as $additional) : 
        $tong += $additional->additional_other_money;
        $tongvat += $additional->additional_other_tax;
    ?>
    
        
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $additional->additional_other_id ?>" class="edit_tr">
            
            <td>
                <input name="check[]" type="checkbox" class="checkbox" value="<?php echo $additional->additional_other_id ?>">
            </td>
            
            <td  class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="additional_other_document_number_<?php echo $additional->additional_other_id; ?>"><?php echo $additional->additional_other_document_number; ?></td>
            <td class="fix" id="additional_other_document_date_<?php echo $additional->additional_other_id; ?>"><?php echo $lib->hien_thi_ngay_thang($additional->additional_other_document_date); ?></td>
            <td class="fix" id="additional_other_additional_date_<?php echo $additional->additional_other_id; ?>"><?php echo $lib->hien_thi_ngay_thang($additional->additional_other_additional_date); ?></td>
            <td class="fix" id="additional_other_comment_<?php echo $additional->additional_other_id; ?>"><?php echo $additional->additional_other_comment; ?></td>
            <td class="fix" data="<?php echo $additional->additional_other_debit ?>" id="additional_other_debit_<?php echo $additional->additional_other_id; ?>"><?php echo isset($account_data[$additional->additional_other_debit])?$account_data[$additional->additional_other_debit]:null; ?></td>
            <td class="fix" data="<?php echo $additional->additional_other_credit ?>" id="additional_other_credit_<?php echo $additional->additional_other_id; ?>"><?php echo isset($account_data[$additional->additional_other_credit])?$account_data[$additional->additional_other_credit]:null; ?></td>
            <td class="fix text-right" id="additional_other_money_<?php echo $additional->additional_other_id; ?>"><?php echo $lib->formatMoney($additional->additional_other_money); ?></td>
            <td class="fix text-right" id="additional_other_tax_percent_<?php echo $additional->additional_other_id; ?>"><?php echo $additional->additional_other_tax_percent; ?></td>
            <td class="fix text-right" id="additional_other_tax_<?php echo $additional->additional_other_id; ?>"><?php echo $lib->formatMoney($additional->additional_other_tax); ?></td>
            <td style="display:none" class="fix" id="additional_other_tax_debit_<?php echo $additional->additional_other_id; ?>"><?php echo $additional->additional_other_tax_debit; ?></td>
            <td style="display:none" class="fix" id="additional_other_invoice_number_<?php echo $additional->additional_other_id; ?>"><?php echo $additional->additional_other_invoice_number; ?></td>
            <td style="display:none" class="fix" id="additional_other_invoice_date_<?php echo $additional->additional_other_id; ?>"><?php echo $additional->additional_other_invoice_date>0?date('d/m/Y',$additional->additional_other_invoice_date):null; ?></td>
            <td style="display:none" class="fix" id="additional_other_invoice_symbol_<?php echo $additional->additional_other_id; ?>"><?php echo $additional->additional_other_invoice_symbol; ?></td>
            <td style="display:none" class="fix" id="additional_other_bank_<?php echo $additional->additional_other_id; ?>"><?php echo $additional->additional_other_bank; ?></td>
            <td style="display:none" class="fix" id="additional_other_bank_check_<?php echo $additional->additional_other_id; ?>"><?php echo $additional->additional_other_bank_check; ?></td>
            <td style="display:none" class="fix" data="<?php echo $additional->additional_other_customer; ?>" id="additional_other_customer_<?php echo $additional->additional_other_id; ?>"><?php echo isset($customer_data[$additional->additional_other_customer])?$customer_data[$additional->additional_other_customer]:null; ?></td>
            
            
            <?php if(!isset($disable_control)){ ?>
            <td class="fix text-right">
                <i class="fa fa-trash" title="Xóa" onclick="del(<?php echo $additional->additional_other_id ?>)"></i>
            </td>
            <?php } ?>
        </tr>


    <?php endforeach; ?>
        <tr style="font-weight:bold; color:red" >
                <td class="fix" colspan="3">Tổng cộng</td>
                <td class="fix"></td>
                <td class="fix"></td>
                <td class="fix"></td>
                <td class="fix"></td>
                <td class="fix"></td>
                <td class="fix text-right"><?php echo $lib->formatMoney($tong) ?></td>
                <td class="fix"></td>
                <td class="fix text-right"><?php echo $lib->formatMoney($tongvat) ?></td>
            </tr>
     
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>
<div class="goback" style="margin: 0 auto"><a href="<?php echo $this->url('additional') ?>">&larr;</a></div>
<div style="display:none" id="lasted"></div>


<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Nghiệp vụ phát sinh </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_additional" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            
                            <td>Số chứng từ</td>
                            <td>
                                <input style="width:80px"  type="text" id="additional_other_document_number"  name="additional_other_document_number" tabindex="1"  required="required" >
                                
                            </td>
                            <td>Ngày chứng từ</td>
                            <td>
                                <input type="text" class="date_mask" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask id="additional_other_document_date"  name="additional_other_document_date" tabindex="2"  required="required" >
                                
                            </td>
                            <td>Ngày phát sinh</td>
                            <td>
                                <input type="text" class="date_mask" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask id="additional_other_additional_date"  name="additional_other_additional_date" tabindex="3"  required="required" >
                                
                            </td>
                        </tr>
                        <tr>
                            <td>Nội dung</td>
                            <td colspan="5">
                                <textarea style="width:100%" name="additional_other_comment" id="additional_other_comment" tabindex="4" required="required" ></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td>Số tiền</td>
                            <td>
                                <input  type="text" id="additional_other_money" class="numbers text-right"  name="additional_other_money" tabindex="5"  required="required" >
                                
                            </td>
                            <td>Thuế GTGT</td>
                            <td>
                                <input  type="text" id="additional_other_tax_percent" class="numbers text-right"  name="additional_other_tax_percent" tabindex="6"  >
                                
                            </td>
                            <td>Tiền thuế GTGT</td>
                            <td>
                                <input  type="text" id="additional_other_tax" class="numbers text-right"  name="additional_other_tax" tabindex="7"  >
                                
                            </td>
                            
                            
                            
                        </tr>
                        <tr>
                            
                            <td>Số HĐ</td>
                            <td>
                                <input style="width:80px"  type="text" id="additional_other_invoice_number"  name="additional_other_invoice_number" tabindex="8"  >
                                
                            </td>
                            <td>Ngày HĐ</td>
                            <td>
                                <input type="text" class="date_mask" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask id="additional_other_invoice_date"  name="additional_other_invoice_date" tabindex="9"  >
                                
                            </td>
                            <td>Ký hiệu</td>
                            <td>
                                <input type="text" id="additional_other_invoice_symbol"  name="additional_other_invoice_symbol" tabindex="10"  >
                                
                            </td>
                            
                        </tr>
                        <tr>
                            <td>Đối tượng</td>
                            <td>
                                <input type="text" id="additional_other_customer"  name="additional_other_customer" tabindex="11"  placeholder="Nhập mã hoặc tên" autocomplete="off" >
                                <ul id="customer_list_id"></ul>
                                <button type="button" style="margin-top: -10px;" class="btn" id="get_customer" onClick="javascript:window.open('<?php echo $this->url('customer') ?>','_blank','location=yes,height=600,width=750,scrollbars=yes,status=yes')"><i class="fa fa-search"></i></button>
                            </td>
                            <td><input type="radio" name="additional_other_bank_check" value="1"> Thu tiền <input type="radio" name="additional_other_bank_check" value="2"> Chi tiền</td>
                            
                            <td>
                                <select name="additional_other_bank" id="additional_other_bank" tabindex="12">
                                    <option value=""> - Tài khoản - </option>
                                    <option value="0">Tiền mặt</option>
                                    <?php foreach ($banks as $bank) { ?>
                                    <option value="<?php echo $bank->bank_id ?>" data="<?php echo $bank->account_number ?>" alt="<?php echo $bank->account_bank ?>" ><?php echo $bank->bank_code ?></option>
                                  <?php } ?>
                                </select>
                            </td>
                            
                        </tr>
                        <tr>
                            <td>Nợ</td>
                            <td>
                                <select style="width:120px" name="additional_other_debit" id="additional_other_debit" tabindex="13" required="required">
                                    <?php foreach ($account_parents as $account_parent) { ?>
                                        <option value="<?php echo $account_parent->account_id ?>"><?php echo $account_parent->account_number.' - '.$account_parent->account_name ?></option>
                                    <?php } ?>
                                </select>
                                
                            </td>
                            <td>Có</td>
                            <td>
                                <select style="width:120px" name="additional_other_credit" id="additional_other_credit" tabindex="14" required="required">
                                    <?php foreach ($account_parents as $account_parent) { ?>
                                        <option value="<?php echo $account_parent->account_id ?>"><?php echo $account_parent->account_number.' - '.$account_parent->account_name ?></option>
                                    <?php } ?>
                                </select>
                                
                            </td>
                            <td>TK thuế</td>
                            <td>
                                <select style="width:120px" name="additional_other_tax_debit" id="additional_other_tax_debit" tabindex="15" >
                                    <option value="">Tài khoản</option>
                                    <?php foreach ($account_parents as $account_parent) { ?>
                                        <option value="<?php echo $account_parent->account_id ?>"><?php echo $account_parent->account_number.' - '.$account_parent->account_name ?></option>
                                    <?php } ?>
                                </select>
                                
                            </td>
                        </tr>
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td>
                                <button type="submit" class="btn btn-primary" tabindex="16"><i class="fa fa-save"></i> Hoàn thành</button>
                            </td>
                            <td>
                                <button type="reset" class="btn" tabindex="17"><i class="fa fa-undo"></i>  Nhập lại</button>
                            </td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
        <div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
    </div>


<script type="text/javascript">

$(".date_mask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
  
$('.add-field').hide();  


$('html').click(function(e) {
    $('#customer_list_id').slideUp(200);
    
});



    $('.edit_tr').click(function(e){
        if(e.target != '[object HTMLButtonElement]' && e.target != '[object HTMLSpanElement]' && !$('.checkbox').is(':focus')) { 
            if(!$('.checkbox').is(':focus')){
                $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
            }
            
            var additional_other_document_number = $(this).find("#additional_other_document_number_"+$(this).attr('id')).text();
            var additional_other_document_date = $(this).find("#additional_other_document_date_"+$(this).attr('id')).text();
            var additional_other_additional_date = $(this).find("#additional_other_additional_date_"+$(this).attr('id')).text();
            var additional_other_comment = $(this).find("#additional_other_comment_"+$(this).attr('id')).text();
            var additional_other_debit = $(this).find("#additional_other_debit_"+$(this).attr('id')).attr('data');
            var additional_other_credit = $(this).find("#additional_other_credit_"+$(this).attr('id')).attr('data');
            var additional_other_customer_name = $(this).find("#additional_other_customer_"+$(this).attr('id')).text();
            var additional_other_customer = $(this).find("#additional_other_customer_"+$(this).attr('id')).attr('data');
            var additional_other_money = $(this).find("#additional_other_money_"+$(this).attr('id')).text();
            var additional_other_bank = $(this).find("#additional_other_bank_"+$(this).attr('id')).text();
            var additional_other_bank_check = $(this).find("#additional_other_bank_check_"+$(this).attr('id')).text();
            var additional_other_tax_percent = $(this).find("#additional_other_tax_percent_"+$(this).attr('id')).text();
            var additional_other_tax = $(this).find("#additional_other_tax_"+$(this).attr('id')).text();
            var additional_other_tax_debit = $(this).find("#additional_other_tax_debit_"+$(this).attr('id')).text();
            var additional_other_invoice_number = $(this).find("#additional_other_invoice_number_"+$(this).attr('id')).text();
            var additional_other_invoice_date = $(this).find("#additional_other_invoice_date_"+$(this).attr('id')).text();
            var additional_other_invoice_symbol = $(this).find("#additional_other_invoice_symbol_"+$(this).attr('id')).text();

            //alert(cost_code);
            $('#yes').val($(this).attr('id'));
            
            $("#additional_other_debit option[value=" + additional_other_debit + "]").attr('selected', 'selected');
            $("#additional_other_credit option[value=" + additional_other_credit + "]").attr('selected', 'selected');
            $('#additional_other_document_number').val(additional_other_document_number);
           // $('#additional_other_document_date').val(additional_other_document_date.replace(/\//g,"-"));
            //$('#additional_other_additional_date').val(additional_other_additional_date.replace(/\//g,"-"));
            $('#additional_other_document_date').val(additional_other_document_date);
            $('#additional_other_additional_date').val(additional_other_additional_date);
            $('#additional_other_comment').val(additional_other_comment);
            $("#additional_other_bank option[value='"+additional_other_bank+"']").attr('selected', 'selected');
            $('input[name="additional_other_bank_check"]').attr("checked", false);
            $('input[name="additional_other_bank_check"][value='+additional_other_bank_check+']').attr('checked',true);
            $('#additional_other_money').val(additional_other_money);
            $('#additional_other_customer').val(additional_other_customer_name);
            $('#additional_other_customer').attr('data',additional_other_customer);
            $('#additional_other_tax_percent').val(additional_other_tax_percent);
            $('#additional_other_tax').val(additional_other_tax);
            $("#additional_other_tax_debit option[value='"+additional_other_tax_debit+"']").attr('selected', 'selected');
            $('#additional_other_invoice_number').val(additional_other_invoice_number);
            $('#additional_other_invoice_date').val(additional_other_invoice_date);
            $('#additional_other_invoice_symbol').val(additional_other_invoice_symbol);

            $( ".add-field" ).dialog( "open" );
        }

        
        
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
     $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);   
     
        $('#additional_other_document_number').val("");
        $('#additional_other_document_date').val("<?php echo date('d/m/Y') ?>");
        $('#additional_other_additional_date').val("<?php echo date('d/m/Y') ?>");
        $('#additional_other_comment').val("");
        $('#additional_other_customer').val("");
        $('#additional_other_customer').attr("data","");
        $('#additional_other_money').val("");
        $("#additional_other_bank option[value='']").attr('selected', 'selected');
        $("#additional_other_debit option[value=0]").attr('selected', 'selected');
        $("#additional_other_credit option[value=0]").attr('selected', 'selected');
        $('input[name="additional_other_bank_check"]').attr("checked", false);
        $('#additional_other_tax_percent').val("");
        $('#additional_other_tax').val("");
        $("#additional_other_tax_debit option[value='']").attr('selected', 'selected');
        $('#additional_other_invoice_number').val("");
        $('#additional_other_invoice_date').val("");
        $('#additional_other_invoice_symbol').val("");
                
        $('.numbers').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.numbers').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

    $( ".add-field" ).dialog( "open" );
}


$(document).ready(function(){
            // Validate form
            $("#add_additional").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    var additional_other_document_number = $('#additional_other_document_number').attr('value');
                    var additional_other_document_date = $('#additional_other_document_date').attr('value');
                    var additional_other_additional_date = $('#additional_other_additional_date').attr('value');
                    var additional_other_comment = $('#additional_other_comment').attr('value');
                    var additional_other_debit = $('#additional_other_debit').attr('value');
                    var additional_other_credit = $('#additional_other_credit').attr('value');
                    var additional_other_money = $('#additional_other_money').attr('value');
                    var additional_other_customer = $('#additional_other_customer').attr('data');
                    var additional_other_bank_check = $('input[name="additional_other_bank_check"]:checked').val();
                    var additional_other_bank = $('#additional_other_bank').attr('value');
                    var additional_other_tax_percent = $('#additional_other_tax_percent').attr('value');
                    var additional_other_tax = $('#additional_other_tax').attr('value');
                    var additional_other_tax_debit = $('#additional_other_tax_debit').attr('value');
                    var additional_other_invoice_number = $('#additional_other_invoice_number').attr('value');
                    var additional_other_invoice_date = $('#additional_other_invoice_date').attr('value');
                    var additional_other_invoice_symbol = $('#additional_other_invoice_symbol').attr('value');

                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/additionalother/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            
                            additional_other_document_number: additional_other_document_number,
                            additional_other_document_date: additional_other_document_date,
                            additional_other_additional_date: additional_other_additional_date,
                            additional_other_comment: additional_other_comment,
                            additional_other_debit: additional_other_debit,
                            additional_other_credit: additional_other_credit,
                            additional_other_customer: additional_other_customer,
                            additional_other_money: additional_other_money,
                            additional_other_bank: additional_other_bank,
                            additional_other_bank_check: additional_other_bank_check,
                            additional_other_tax_percent: additional_other_tax_percent,
                            additional_other_tax: additional_other_tax,
                            additional_other_tax_debit: additional_other_tax_debit,
                            additional_other_invoice_number: additional_other_invoice_number,
                            additional_other_invoice_date: additional_other_invoice_date,
                            additional_other_invoice_symbol: additional_other_invoice_symbol,
                            yes: yes,

                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Tài khoản đã tồn tại") {
                                    setTimeout(function() {
                                            sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                          }, 200);
                                }
                            }
                            else{
                                if (answer.trim() != "Tài khoản đã tồn tại") {
                                    setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                }
                                
                            }
                        }
                    });
                    return false;
                     
                 }
            });


    $('#additional_other_customer').keyup(function(){
        var rowIndex = 0;
        var keyword = $(this).val();
        if(keyword != ""){
          $.ajax({
              url: '<?php echo BASE_URL ?>/additionalother/getCustomer',
              type: 'POST',
              data: {keyword:keyword, offset:rowIndex},
              success:function(data){
                  $('#customer_list_id:eq('+rowIndex+')').slideDown(200);
                  $('#customer_list_id:eq('+rowIndex+')').html(data);
              }
          });
        }

        if ($('#additional_other_customer:eq('+rowIndex+')').val() == "" || $('#additional_other_customer:eq('+rowIndex+')').attr('data') == "") {
          $('#additional_other_customer:eq('+rowIndex+')').attr('data',"");
        }
    });

   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });

    $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-]/g, "")
        ;
      });
    });
    

});

function set_item_customer(value,code,name,company,mst,address,vitri) {
    $('#additional_other_customer:eq('+vitri+')').val(code);
    $('#additional_other_customer:eq('+vitri+')').attr("data",value);
    $('#customer_company:eq('+vitri+')').val(company);
    $('#customer_mst:eq('+vitri+')').val(mst);
    $('#customer_address:eq('+vitri+')').val(address);
    $('#customer_list_id').hide();
    $('#additional_other_customer:eq('+vitri+')').focus();
}
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}

</script>
<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

$("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:300,
            width:400,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });


 
var x = "<?php echo $limit ?>";
$('#chonloc option[value='+x+']').attr('selected','selected');
var s = "<?php echo $trangthai ?>";
$('#sl_status option[value='+s+']').attr('selected','selected');


</script>
</div>

<script type="text/javascript">


$( ".add-field" ).dialog({
    autoOpen: false,
    modal: true,
    width: "auto",
    title: "Phát sinh",
    hide: 'fold',
    show: 'blind'
});



$(".show").click(function(){
    $("#winpopup").dialog({
        draggable:true,
        modal: true,
        autoOpen: false,
        width: "90%",
        resizable: false,
        position: "top",
        title:'Chi tiết',
        buttons: {
            OK: function() {
                $( this ).dialog( "close" );
            },
            Cancel: function() {
                $( this ).dialog( "close" );
            }
        }
    });
    $("#winpopup").load($(this).attr('href'));
    $("#winpopup").dialog("open");
    return false;
});

var pickerOpay2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+0",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $(".ngay").datepicker(pickerOpay2);


var pickerOpts3 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts3);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        showWeek: true,
        weekHeader: 'Tuần',
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);

    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        changeMonth: true,
        changeYear: true,
        dateFormat: 'mm/yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function() {
                $("#chonngaytao").change();
         },
         
    };  
    $("#chonngaytao").datepicker(pickerOpts);

    $("#chonngaytao").change(function(){
        var month = parseInt($("#ui-datepicker-div .ui-datepicker-month :selected").val());
        var year = parseInt($("#ui-datepicker-div .ui-datepicker-year :selected").val());
        $(this).datepicker('setDate', new Date(year, month, 1));

        var firstDay = new Date(year, month, 1);

        $('#batdau').datepicker("setDate", firstDay );
    });

    var pickerOpts5 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        changeMonth: true,
        changeYear: true,
        dateFormat: 'mm/yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function() {
                $("#chonngaytaobatdau").change();
         },
         
    };  
    $("#chonngaytaobatdau").datepicker(pickerOpts5);

    $("#chonngaytaobatdau").change(function(){
        var month = parseInt($("#ui-datepicker-div .ui-datepicker-month :selected").val());
        var year = parseInt($("#ui-datepicker-div .ui-datepicker-year :selected").val());
        $(this).datepicker('setDate', new Date(year, month, 1));

        var lastDay = new Date(year, month+1, 0);
        $('#ketthuc').datepicker("setDate", lastDay );
    });

    $(".monthPicker").focus(function () {
        $(".ui-datepicker-calendar").hide();
        $("#ui-datepicker-div").position({
            my: "center top",
            at: "center bottom",
            of: $(this)
        });    
    });
</script>

