
<div id="loading"></div>
<div id="winpopup"></div>
<section class="content-header">
    <h1>PHÂN QUYỀN HỆ THỐNG</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="<?php echo $this->url('permission') ?>">Phân quyền</a></li>
  </ol>
</section>

<form id="add_permission" role="form" method="post" action="" enctype="multipart/form-data">
<div class="box box-primary">
  <div class="row">
    <div class="col-md-2 col-xs-6">
      <div class="box-body">
        <div class="form-group">
          <label for="role">Nhóm người dùng</label>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-xs-6">
      <div class="box-body">
        <div class="form-group">
          <select id="role_name" name="role_name">
            <option>Chọn</option>
            <?php foreach ($roles as $role): ?>
            <option value="<?php echo $role->role_id ?>" ><?php echo $role->role_name ?></option>
          <?php endforeach; ?>
          </select>
        </div>
      </div>
    </div>
    <div class="col-md-2 col-xs-6">
      <div class="box-body">
        <div class="form-group">
          <label for="user">Người dùng</label>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-xs-6">
      <div class="box-body">
        <div class="form-group">
          <select id="user_name" name="user_name">
          </select>
        </div>
      </div>
    </div>
    <div class="col-md-2 col-xs-6">
      <div class="box-body">
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Lưu</button>
        </div>
      </div>
    </div>
  </div>
  <table class="table_data">
    <thead>
      <tr>
        <th class="fix">Nghiệp vụ</th>
        <th class="fix">Truy cập</th>
        <th class="fix">Cập nhật</th>
      </tr>
    </thead>
    <tbody>
      
      <tr class="edit_tr">
        <td class="fix"><b>Hệ thống</b></td>
        <td class="fix"><input type="checkbox" onclick="check_all('hethong', this)" value=""></td>
        <td class="fix"><input type="radio" data="hethong2" value=""></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Thông tin doanh nghiệp</td>
        <td class="fix"><input type="checkbox" id="ttdoanhnghiep" value="info" class="hethong"></td>
        <td class="fix"><input type="radio" id="ttdoanhnghiep2" value="info" class="hethong2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Tài khoản</td>
        <td class="fix"><input type="checkbox" id="taikhoanuser" value="user" class="hethong"></td>
        <td class="fix"><input type="radio" id="taikhoanuser2" value="user" class="hethong2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Phân quyền</td>
        <td class="fix"><input type="checkbox" id="phanquyen" value="permission" class="hethong"></td>
        <td class="fix"><input type="radio" id="phanquyen2" value="permission" class="hethong2"></td>
      </tr>
      <tr class="edit_tr">
        <td class="fix">&nbsp;&nbsp; - Sao lưu & Phục hồi</td>
        <td class="fix"><input type="checkbox" id="backup" value="backup" class="hethong"></td>
        <td class="fix"><input type="radio" id="backup2" value="backup" class="hethong2"></td>
      </tr>
    </tbody>
  </table>
</div>
</form>

<script type="text/javascript">
function check_all(class_name, obj) {
    var items = document.getElementsByClassName(class_name);
    if(obj.checked == true) 
    {
      for(i=0; i < items.length ; i++)
        items[i].checked = true;
    }
    else { 
      for(i=0; i < items.length ; i++)
        items[i].checked = false;
    }
}
$("input[type='radio']").click(function()
{
  var previousValue = $(this).attr('previousValue');
  var name = $(this).attr('name');
  var items = document.getElementsByClassName($(this).attr('data'));

  if (previousValue == 'checked')
  {
    $(this).removeAttr('checked');
    $(this).attr('previousValue', false);
    for(i=0; i < items.length ; i++)
        items[i].checked = false;
  }
  else
  {
    $("input[name="+name+"]:radio").attr('previousValue', false);
    $(this).attr('previousValue', 'checked');
    for(i=0; i < items.length ; i++)
        items[i].checked = true;
  }
});


$('#role_name').change(function(){
  var val = $(this).val();

  $.ajax({

      url: '<?php echo BASE_URL ?>/permission/getrolepermission',

      type: 'POST',

      data: {data:val},

      success:function(data){
          $('input[type=checkbox]').prop('checked',false);
          if (data.trim() != "") {
            var data = jQuery.parseJSON(data);
            $.each(data, function(i, item) {
                $('input[type=checkbox][value='+data[i]+']').prop('checked',true);
            })
          }
      }

  });
  $.ajax({

      url: '<?php echo BASE_URL ?>/permission/getuser',

      type: 'POST',

      data: {data:val},

      success:function(data){
          $('#user_name').html(data);
      }

  });

  $.ajax({

      url: '<?php echo BASE_URL ?>/permission/getrolepermission2',

      type: 'POST',

      data: {data:val},

      success:function(data){
          $('input[type=radio]').prop('checked',false);
          if (data.trim() != "") {
            var data = jQuery.parseJSON(data);
            $.each(data, function(i, item) {
                $('input[type=radio][value='+data[i]+']').prop('checked',true);
                $('input[type=radio][value='+data[i]+']').attr('previousValue','checked');
            })
          }
      }

  });
});

$('#user_name').change(function(){
  var val = $(this).val();
  $.ajax({

      url: '<?php echo BASE_URL ?>/permission/getpermission',

      type: 'POST',

      data: {data:val},

      success:function(data){
        $('input[type=checkbox]').prop('checked',false);
        if (data.trim() != "") {
          var data = jQuery.parseJSON(data);
          $.each(data, function(i, item) {
              $('input[type=checkbox][value='+data[i]+']').prop('checked',true);
          })
        }
          
      }

  });

  $.ajax({

      url: '<?php echo BASE_URL ?>/permission/getpermission2',

      type: 'POST',

      data: {data:val},

      success:function(data){
        $('input[type=radio]').prop('checked',false);
        if (data.trim() != "") {
          var data = jQuery.parseJSON(data);
          $.each(data, function(i, item) {
              $('input[type=radio][value='+data[i]+']').prop('checked',true);
              $('input[type=radio][value='+data[i]+']').attr('previousValue','checked');
          })
        }
          
      }

  });
});

$("#add_permission").validate({
  errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
  rules: {
      
  },
  submitHandler: function(form) {
    var role = $('#role_name').val();
    var user = $('#user_name').val();
    var str = [];
    var act = {};

    $('input[type=checkbox]').each(function() { 
        if($(this).is(':checked')){
          var val = $(this).val();
          if ($(this).val() != "") {
            str.push(val);

            if($('input[type=radio][value='+val+']').is(':checked')){
              act[val] = val;
            }
            
          }
        }
    });
    if(role>0){
      $.ajax({
        type: "POST", // phương thức gởi đi
        url: "<?php echo BASE_URL ?>/permission/setpermission", // nơi mà dữ liệu sẽ chuyển đến khi submit
        data: {
            data: str,
            act: act,
            user: user,
            role: role,
            }, // giá trị post
        success: function(answer){ // if everything goes well
            alert(answer);
            
        }
      });
    }
    return false;
  }
});
</script>